name: require pull request

on:
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  job:
    name: require pull request
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
